---
- name: Setting Up Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing Nginx
    ansible.builtin.yum:
     name: nginx
     state: present

  - name: Starting Nginx Service
    ansible.builtin.service:
      name: nginx
      state: started
      
