---
- name: Using Variables
  hosts: web
  # become: yes
  # Declaring variables In Play Level
  vars:
    user-name: siva
    course: DevOps
  tasks:
  # - name: Printing Message
  #   ansible.builtin.debug:
  #     msg: "Hellow Siva"
  - name: Printing username
    ansible.builtin.debug:
      msg: "Hellow {{ user-name }}"
  - name: Printing Course
    ansible.builtin.debug:
      msg: "You are learning {{course}}"