---
- name: Declaring Variables In Tasks
  hosts: localhost
  vars:
    money: "1 cr"
    land: "1 acr"
  tasks:
  - name: Printing Parent/paly level variables
    ansible.builtin.debug:
      msg: "U got Money of {{money}} and Land of {{land}}"

  - name: Printing children/Task and parent/play Variables
    vars: # Declaring Variables at task level
      money: "2 cr"
      land: "5 acr"
      houses: "2"
    ansible.builtin.debug:
      msg: "Siva increased property to money {{money}} lamd {{land}} houses {{houses}}"

  - name: Check Task-Task variables
    ansible.builtin.debug:
      msg: "Siva Has Houses {{houses}}"
