---
- name: Checking mapped Loop
  hosts: localhost
  tasks:
  - name: Configuring packages
    become: true
    ansible.builtin.yum:
      name: "{{ item.name }}"
      state: "{{ item.action }}"
    loop:
    - { name: "tree", action: "absent" }
    - { name: "nginx", action: "present" }
    - { name: "httpd", action: "absent" }
    - { name: "maven", action: "present" }
